### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by matthewvalimaki** [silverbulleters/gherkin-autocomplete#35]
Generally I am having trouble with the autocomplete matching anything.

For example I have a step `I am logged in` and if I type `Then I` the list is filtered apparently correctly with the letter `I` highlighted as expected. But now if I continue `Then I ` (so added a space) the list changes dropping those which should be still there. Further if I do `Then I a` the list completely disappears.

So knowing that text matching is complex I was wondering could we introduce an option where it simply looks for exactly what has been typed?

**Comment by nixel2007** [comment]
Looks like it needs some investigation. @pumbaEO could you try to look in? Maybe some changes in autocomple from 1c-syntax should be "cherry-picked" here

**Comment by artbear** [comment]
The current problem was fixed by #44 

@matthewvalimaki check it
