### ISSUE TITLE
Некорретная работа при подборе с использованием пробела

### ISSUE THREAD

**Issue by PashaMak** [silverbulleters/gherkin-autocomplete#38]
Некорретная работа при подборе с использованием пробела
![default](https://user-images.githubusercontent.com/24808007/38014449-ff69d35a-3292-11e8-875e-be50ed951b90.png)

**Comment by artbear** [comment]
@PashaMak По скриншоту не видно, что где-то проблемы с пробелом.

на скриншоте картина нечеткого поиска, реализованного в плагине - ищутся все шаги, в которых одновременно есть все набранные символы - т.е. `я`, `п`, `р` без учета регистра

А вот некорректная работа с пробельными и другими символами доработана мной в #44 
Теперь после ввода, например, пробела подсказка продолжает работать, а не заканчивает свою работу.
