### ISSUE TITLE
Ошибка при обновлении кэша шагов

### ISSUE THREAD

**Issue by acherepninss** [silverbulleters/gherkin-autocomplete#7]
1. Указываю путь к папке Libraries для Vanessa-Behavior в параметрах пользователя
2. Пытаюсь обновить кэш шагов
3. Получаю ошибку

![image](https://cloud.githubusercontent.com/assets/24224164/21012111/881a8a36-bd65-11e6-908d-3c1eaf6c8e2c.png)

**Comment by nixel2007** [comment]
@acherepninss вот эта фича?

**Comment by acherepninss** [comment]
@nixel2007 ага

**Comment by nixel2007** [comment]
@acherepninss постараюсь посмотреть сегодня.

**Comment by artbear** [comment]
Прошло почти 2 года, видимо, проблема или решена, или @acherepninss перестал пользоваться :(

закрываю.

@acherepninss Если проблема повторяется, переоткрывай
