### ISSUE TITLE
Не видит шаги из библиотеки vanessa-bihavior

### ISSUE THREAD

**Issue by sdoronin** [silverbulleters/gherkin-autocomplete#8]

**Comment by nixel2007** [comment]
Содержание settings.json (в воркспейсе и пользовательского), версию vsc и плагина, расположение VB на диске, версию OS

**Comment by sdoronin** [comment]
Параметры пользователя:
// Поместите параметры в этот файл, чтобы перезаписать параметры по умолчанию.
{
    "gherkin-autocomplete.featureLibraries": [
      "C:/Users/J2/Documents/erp/tools/vanessa-behavior/features/Libraries"  
    ]
}
Параметры рабочей области отсутствуют.
Версия VSC 1.8.1.
Плагин 1.1.1
Расположение VB C:/Users/J2/Documents/erp/tools/vanessa-behavior
OS Win7 64

**Comment by nixel2007** [comment]
Такое чувство, что что-то именно в семерке.
@alehinsasha у тебя в твоей семерошной виртуалке работает автокомплит?

**Comment by sdoronin** [comment]
Виртуалки нет у меня, если я именно то понимаю.

**Comment by nixel2007** [comment]
@sdoronin нет, это была просьба к Саше проверить на его семерке :)

**Comment by alehinsasha** [comment]
@nixel2007 ок, она на домашнем ПК, проверю как доберусь.

**Comment by nixel2007** [comment]
Просьба проверить на версии 1.1.2
Если ошибка повторится - переоткрывай ишуз.
